name: "Dahua2MQTT"
description: "My first real add-on!"
version: "0.0.1"
slug: "dahua2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  52345/tcp: 52345