name: "Dahua2MQTT"
description: "Get the HTTP alarms from your Dahua NVR (or other) in Home Assistant's MQTT broker"
version: "0.1.2"
slug: "dahua2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: services

ports:
  52345/tcp: 52345

options:
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
schema:
  mqtt_broker: str
  mqtt_port: port
  mqtt_username: str
  mqtt_password: password
